name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'tools/**'
      - '**/*.md'
      - '*.code-workspace'

  pull_request:
    branches: [main]
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'tools/**'
      - '**/*.md'
      - '*.code-workspace'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package:
    uses: ./.github/workflows/package.yml

  openapi:
    uses: ./.github/workflows/openapi.yml

  # release:
  #   uses: ./.github/workflows/release.yml
  #   needs: [build, package, openapi]
  #   secrets: inherit
