name: Release

on: workflow_call

jobs:
  version:
    uses: ./.github/workflows/version.yml

  publish_nuget:
    uses: ./.github/workflows/publish_nuget.yml
    secrets:
      SLEET_CONNECTIONSTRING: ${{ secrets.SLEET_CONNECTIONSTRING }}

  publish_npm:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/publish_npm.yml
    needs: version
    with:
      path: sdks/typescript/entities
      version: ${{ needs.version.outputs.fullSemVer }}
    secrets:
      NPM_API_KEY: ${{ secrets.NPM_API_KEY }}

  publish_container:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/publish_image.yml
    secrets:
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}

  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [version, publish_container, publish_npm]

    steps:
      - name: Create Release
        uses: actions/github-script@v7
        with:
          script: |
            const releaseResult = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v${{ needs.version.outputs.fullSemVer }}',
              name: 'v${{ needs.version.outputs.fullSemVer }}',
              prerelease: true,
              body: 'prerelease'
            });

            const release = releaseResult.data;
